import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Frontpage from '../components/front-page/frontpage'
import Aboutme from '../components/about-me/aboutme'
import Myskills from '../components/my-skills/myskills'
import Portfolio from '../components/portfolio/portfolio'
import Blog from '../components/blog/blog'
import Contactme from '../components/contact-me/contactme'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>O meu portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Frontpage />
        <Aboutme />
        <Myskills />
        <Portfolio />
        <Blog />
        <Contactme/>

      </main>

    </div>
  )
}

export default Home
