import type { NextPage } from "next";
import Head from "next/head";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import styles from "../styles/Home.module.scss";

import Frontpage from "../components/front-page/frontpage";
import Aboutme from "../components/about-me/aboutme";
import Myskills from "../components/my-skills/myskills";
import Portfolio from "../components/portfolio/portfolio";
import Blog from "../components/blog/blog";
import Contactme from "../components/contact-me/contactme";
import Project from "../components/project/project";
import Post from "../components/post/post";
import Menu from "../atoms/menu/menu";
import Sidebar from "../components/sidebar/sidebar";

import { useState } from "react";
import { menuEnabledAtom } from "../atoms/menu/atoms";
import { useRecoilValue } from "recoil";

const Home: NextPage = () => {
  const [projectId, setProjectId] = useState(0);
  const [postId, setPostId] = useState(0);
  const showOrHide = useRecoilValue(menuEnabledAtom);

  const onSelectProject = (id: number) => {
    setProjectId(id);
  };
  const onSelectPost = (id: number) => {
    setPostId(id);
  };
  const onResetProject = (zero: number) => {
    setProjectId(zero);
  };
  const onResetPost = (zero: number) => {
    setPostId(zero);
  };

  return (
    <div>
      <Head>
        <title>O meu portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </Head>
      <div className={styles.container} data-amount={`${showOrHide}`}>          
        <nav className={styles.nav}>
          <Sidebar/>
          <Menu />
        </nav>
        <main className={styles.main}>
          <Frontpage />
          <Aboutme />
          <Myskills />
          <Portfolio selectProject={onSelectProject} />
          <Blog selectPost={onSelectPost} />
          <Contactme />
          <Project project={projectId} resetProject={onResetProject} />
          <Post
            post={postId}
            resetPost={onResetPost}
            selectPost={onSelectPost}
          />
          <Menu/>
        </main>
      </div>
    </div>

  );
};

export default Home;
